<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Gateway\Module'                      => __DIR__ . '/Module.php',
  'Gateway\Controller\BoardController'  => __DIR__ . '/src/Gateway/Controller/BoardController.php',
  'Gateway\Controller\ServerController' => __DIR__ . '/src/Gateway/Controller/ServerController.php',
  'Gateway\Form\ServerForm'             => __DIR__ . '/src/Gateway/Form/ServerForm.php',
  'Gateway\Model\Board'                 => __DIR__ . '/src/Gateway/Model/Board.php',
  'Gateway\Model\BoardTable'            => __DIR__ . '/src/Gateway/Model/BoardTable.php',
  'Gateway\Model\Server'                => __DIR__ . '/src/Gateway/Model/Server.php',
  'Gateway\Model\ServerTable'           => __DIR__ . '/src/Gateway/Model/ServerTable.php',
);
