<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Idip\Module'                    => __DIR__ . '/Module.php',
  'Idip\Controller\IdipController' => __DIR__ . '/src/Idip/Controller/IdipController.php',
  'Idip\Model\Idip'                => __DIR__ . '/src/Idip/Model/Idip.php',
  'Idip\Model\IdipData'            => __DIR__ . '/src/Idip/Model/IdipData.php',
  'Idip\Model\IdipRequest'         => __DIR__ . '/src/Idip/Model/IdipRequest.php',
  'Idip\Model\IdipResponse'        => __DIR__ . '/src/Idip/Model/IdipResponse.php',
  'ServerApi'                      => 'vendor/yuxiang/socket_api.php',//yuxiang -> Send GM command to GS
);
