<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'User\Module'                  => __DIR__ . '/Module.php',
  'User\Controller\QqController' => __DIR__ . '/src/User/Controller/QqController.php',
  'User\Controller\WxController' => __DIR__ . '/src/User/Controller/WxController.php',
  'User\Model\QQ'                => __DIR__ . '/src/User/Model/QQ.php',
  'User\Model\User'              => __DIR__ . '/src/User/Model/User.php',
  'User\Model\WX'                => __DIR__ . '/src/User/Model/WX.php',
  'SnsNetwork'                   => 'vendor/tencent/lib/SnsNetwork.php',//tencent-SnsNetwork ref
  'SnsSigCheck'                  => 'vendor/tencent/lib/SnsSigCheck.php',//tencent-SnsSigCheck ref
);
