<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'gateway/server/add'     => __DIR__ . '/view/gateway/server/add.phtml',
    'gateway/server/close'   => __DIR__ . '/view/gateway/server/close.phtml',
    'gateway/server/edit'    => __DIR__ . '/view/gateway/server/edit.phtml',
    'gateway/server/index'   => __DIR__ . '/view/gateway/server/index.phtml',
    'gateway/server/merge'   => __DIR__ . '/view/gateway/server/merge.phtml',
    'gateway/server/migrate' => __DIR__ . '/view/gateway/server/migrate.phtml',
    'gateway/server/open'    => __DIR__ . '/view/gateway/server/open.phtml',
);
