<?php
$title = 'Add new server';
$this->headtitle($title);
?>
<h1><?php echo $this->escapehtml($title); ?></h1>
<?php 
$form->setAttribute('action', $this->url('server', array('action' => 'add')));
$form->prepare();
// echo $this->formcollection($form);
echo $this->form()->openTag($form);
echo $this->formhidden($form->get('id'));
?>

<div><?php echo $this->formrow($form->get('area_id')); ?></div>
<div><?php echo $this->formrow($form->get('plat_id')); ?></div>
<div><?php echo $this->formrow($form->get('partition')); ?></div>
<div><?php echo $this->formrow($form->get('name')); ?></div>
<div><?php echo $this->formrow($form->get('ip')); ?></div>
<div><?php echo $this->formrow($form->get('port')); ?></div>
<div><?php echo $this->formrow($form->get('db_host')); ?></div>
<div><?php echo $this->formrow($form->get('db_port')); ?></div>
<div><?php echo $this->formrow($form->get('db_name')); ?></div>
<div><?php echo $this->formrow($form->get('db_user')); ?></div>
<div><?php echo $this->formrow($form->get('db_pass')); ?></div>

<div><?php echo $this->formsubmit($form->get('submit')); ?><?php echo $this->formbutton($form->get('back'), 'Back'); ?></div>
<?php echo $this->form()->closeTag(); ?>

<?php
$this->inlinescript()->captureStart();
echo <<<JS
    $('#btnBack').click(function() {
        window.location.href = '/server';
    });
JS;
$this->inlinescript()->captureEnd();
?>