<?php
use Gateway\Model\Server;

$title = 'Servers List';
$this->headtitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('server', array('action' => 'add')); ?>">Add new server</a>
</p>

<form action="<?php echo $this->url('server', array('action' => 'merge')); ?>" method="post">
<div>
<table class="table">
<thead>
<tr>
    <th>Sel.</th>
    <th>Area</th>
    <th>Plat</th>
    <th>Partition</th>
    <th>Name</th>
    <th>IP</th>
    <th>Port</th>
    <th>DB-Host</th>
    <th>DB-Name</th>
    <th>DB-User</th>
    <th>DB-Pass</th>
    <th>Status</th>
    <th>Open</th>
    <th>Opt.</th>
</tr>
</thead>
<tbody>
<?php foreach ($servers as $server) { ?>
<tr>
    <td><input id="check_<?php echo $server->id; ?>" name="server_ids[]" type="checkbox"></td>
    <td><?php echo $tx_area_list[$server->area_id]; ?></td>
    <td><?php echo $tx_plat_list[$server->plat_id]; ?></td>
    <td><?php echo $server->partition; ?></td>
    <td><?php echo $server->name; ?></td>
    <td><?php echo $server->ip; ?></td>
    <td><?php echo $server->port; ?></td>
    <td><?php echo $server->db_host . ':' . $server->db_port; ?></td>
    <td><?php echo $server->db_name; ?></td>
    <td><?php echo $server->db_user; ?></td>
    <td><?php echo $server->db_pass; ?></td>
    <td><?php echo $status_list[$server->status]; ?></td>
    <td><?php echo $server->open_time; ?></td>
    <td>
        <a href="<?php echo $this->url('server', array('action' => 'edit', 'id' => $server->id)); ?>">Edit</a>
<?php if ($server->status == Server::STATUS_CLOSED) { ?>
        <a href="<?php echo $this->url('server', array('action' => 'open', 'id' => $server->id)); ?>">Open</a>
<?php } elseif ($server->status == Server::STATUS_OPEN) { ?>
        <a href="<?php echo $this->url('server', array('action' => 'close', 'id' => $server->id)); ?>">Close</a>
<?php } ?>
        <a href="<?php echo $this->url('server', array('action' => 'migrate', 'id' => $server->id)); ?>">Migrate</a>
    </td>
</tr>
<?php } ?>
</tbody>
</table>
</div>
<div>
    <input type="submit" name="btnMerge" id="btnMerge" value="Merge">
</div>
</form>