<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Module'                     => __DIR__ . '/Module.php',
  'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
  'Application\Model\Application'          => __DIR__ . '/src/Application/Model/Application.php',
  'Application\Service\CxLogFactory'       => __DIR__ . '/src/Application/Service/CxLogFactory.php',
  'SnsNetwork'                             => 'vendor/tencent/lib/SnsNetwork.php',//tencent-SnsNetwork ref
  'ServerApi'                              => 'vendor/yuxiang/socket_api.php',//yuxiang -> Send GM command to GS
);
