<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Account\Module'                       => __DIR__ . '/Module.php',
  'Account\Controller\AccountController' => __DIR__ . '/src/Account/Controller/AccountController.php',
  'Account\Model\Account'                => __DIR__ . '/src/Account/Model/Account.php',
  'ServerApi'                            => 'vendor/yuxiang/socket_api.php',//yuxiang -> Send GM command to GS
  'SnsSigCheck'                          => 'vendor/tencent/lib/SnsSigCheck.php',//tencent-SnsSigCheck ref
);
